name: simu_col
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - matplotlib=3.2.2
  - pandas=1.3.5
  - pyqt=5.9.2
  - python=3.7.11
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.5.5
  - qtpy=1.9.0
  - cudatoolkit=11.3.1
  - pytorch==1.11.0
  - scikit-learn=1.0.2
  - pip:
    - protobuf==3.20.1
    - lz4==4.0.0
    - keyboard==0.13.5
    - dm-tree==0.1.7
    - gym==0.18.0
    - numpy==1.21.6
    - ray[tune]==1.12.0
    - redis==4.2.2
    - tensorboard==1.15.0
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.5
    - opencv-python==4.6.0.66
    - pyqtgraph==0.10.0
    - scikit-learn==1.0.2
